# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0002_auto_20160229_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='listaObras',
            field=models.ManyToManyField(blank=True, to='cultura.Obra'),
        ),
    ]
