# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoComentario', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeComunidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-Feira'), ('TER', 'Terça-Feira'), ('QUA', 'Quarta-Feira'), ('QUI', 'Quinta-Feira'), ('SEX', 'Sexta-Feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('enderecoOficial', models.CharField(max_length=500)),
                ('enderecoUsual', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webservice.Elemento')),
                ('listaObras', models.ManyToManyField(to='webservice.Obra')),
            ],
            bases=('webservice.elemento', models.Model),
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webservice.Elemento')),
                ('nomeProprietario', models.CharField(max_length=80)),
            ],
            bases=('webservice.elemento',),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webservice.Elemento')),
                ('dataEvento', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
            ],
            bases=('webservice.elemento', models.Model),
        ),
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webservice.Elemento')),
            ],
            bases=('webservice.elemento', models.Model),
        ),
        migrations.AddField(
            model_name='ponto',
            name='pontoElemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.Elemento'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='comunidadeElemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.Comunidade'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='listaTags',
            field=models.ManyToManyField(to='webservice.Tag'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='elementoComentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.Elemento'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='nomeUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.Usuario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='listaDatas',
            field=models.ManyToManyField(to='webservice.Datas'),
        ),
        migrations.CreateModel(
            name='EstabelecimentoFixo',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webservice.Estabelecimento')),
                ('listaDatas', models.ManyToManyField(to='webservice.Datas')),
            ],
            bases=('webservice.estabelecimento', models.Model),
        ),
        migrations.CreateModel(
            name='EstabelecimentoMovel',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webservice.Estabelecimento')),
            ],
            bases=('webservice.estabelecimento', models.Model),
        ),
        migrations.AddField(
            model_name='agenda',
            name='agendaMovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.EstabelecimentoMovel'),
        ),
    ]
