# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoComentario', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeComunidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('enderecoOficial', models.CharField(max_length=500)),
                ('enderecoUsual', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('comunidadeElemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comunidade')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='elemento',
            name='listaTags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='elementoComentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Elemento'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='nomeUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
