# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160229_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
