# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160229_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
