# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_elemento_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
